python3 main.py ../../AMGCL_KT/amgcl_data/ibmpg1/ibmpg.G.txt ibmpg1.txt
python3 main.py ../../AMGCL_KT/amgcl_data/ibmpg2/ibmpg.G.txt  ibmpg2.txt
python3 main.py ../../AMGCL_KT/amgcl_data/ibmpg3/ibmpg.G.txt   ibmpg3.txt
python3 main.py ../../AMGCL_KT/amgcl_data/ibmpg4/ibmpg.G.txt    ibmpg4.txt
python3 main.py ../../AMGCL_KT/amgcl_data/ibmpg5/ibmpg.G.txt     ibmpg5.txt
python3 main.py ../../AMGCL_KT/amgcl_data/ibmpg6/ibmpg.G.txt      ibmpg6.txt
python3 amg_plot.py ibmpg1.txt      ./V_DIR/ibmpg1.PNG 
python3 amg_plot.py  ibmpg2.txt     ./V_DIR/ibmpg2.PNG 
python3 amg_plot.py   ibmpg3.txt    ./V_DIR/ibmpg3.PNG 
python3 amg_plot.py    ibmpg4.txt   ./V_DIR/ibmpg4.PNG 
python3 amg_plot.py     ibmpg5.txt  ./V_DIR/ibmpg5.PNG 
python3 amg_plot.py      ibmpg6.txt ./V_DIR/ibmpg6.PNG 
